---
name: "PR Warning"

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  warning:
    name: "Display Warning"
    runs-on: ubuntu-latest
    steps:
      - name: Show Warning
        run: |
          echo "::warning::This is a warning message for the pull request"

